module.exports = {
  base: [{
    protocol: 'amqp',
    hostname: '10.10.0.22',
    port: 5672,
    username: 'bmpos_beta_backend_base',
    password: 'WqKa4gzIlU0pFUAgEWCn',
    vhost: '/bmpos/beta/backend/base',
    heartbeat: 2,
  }],
  base_dev_V2: [{
    protocol: 'amqp',
    hostname: '10.10.0.22',
    port: 5672,
    username: 'bmpos_beta_backend_base_v2',
    password: 'a3XxjzPgkhsn8lNY6Pbj',
    vhost: '/bmpos/beta/backend/base_v2',
    heartbeat: 2,
  }],
  company: [{
    protocol: 'amqp',
    hostname: '10.10.0.22',
    port: 5672,
    username: 'bmpos_beta_backend_company',
    password: '4o7CGt0Hmcdf0yEFO2RQ',
    vhost: '/bmpos/beta/backend/company',
    heartbeat: 2,
  }],
  company_dev_V2: [{
    protocol: 'amqp',
    hostname: '10.10.0.22',
    port: 5672,
    username: 'bmpos_beta_backend_company_v2',
    password: 'YUWdEQZd9X4D6qWAyiK3',
    vhost: '/bmpos/beta/backend/company_v2',
    heartbeat: 2,
  }],
  transaction: [{
    protocol: 'amqp',
    hostname: '10.10.0.22',
    port: 5672,
    username: 'bmpos_dev_backend_transaction',
    password: 'MjqjchkYZMRvJpCC5xUA',
    vhost: '/bmpos/dev/backend/transaction',
    heartbeat: 2,
  }],
  transaction_dev_V2: [{
    protocol: 'amqp',
    hostname: '10.10.0.22',
    port: 5672,
    username: 'bmpos_dev_backend_transaction_v2',
    password: 'eXbg4YXND4RtdT8G3RlS',
    vhost: '/bmpos/dev/backend/transaction_v2',
    heartbeat: 2,
  }],
  // transaction_beta_V3: [{
  //   protocol: 'amqp',
  //   hostname: '10.10.0.22',
  //   port: 5672,
  //   username: 'bmpos_dev_backend_transaction',
  //   password: 'MjqjchkYZMRvJpCC5xUA',
  //   vhost: '/bmpos/dev/backend/transaction_v3',
  //   heartbeat: 2,
  // }],
};